language: node_js
node_js: stable
sudo: required
dist: trusty
install:
  - npm cache clean
  - npm install npm@latest -g
  - npm install
build:
  - npm run test
  - npm run build
deploy:
  provider: azure_web_apps